// Generated by https://Quicktype.in

import { ICategoria } from "./ICategoria";

export interface ILibro {
    id:                     number;
    autor_id:               number;
    titulo:                 string;
    isbn:                   number;
    fecha_de_publicacion:   string;
    editorial:              string;
    numero_de_paginas:      number;
    serie:                  string;
    clasificaion:           string;
    estado:                 string;
    situacion:              string;
    categoria:              ICategoria;
}

export interface IColumn {
  key: string;
  label: string;
}
const ColumLibro:IColumn[] = [
  {
    key: "id",
    label: "ID",
  },
  {
    key: "titulo",
    label: "TITULO",
  },
  {
    key: "pagina",
    label: "PAGINA",
  },
  {
    key: "situacion",
    label: "SITUACION",
  },
  /*{
    key: "thumbnailUrl",
    label: "Imagen",
  },*/
];

export default ColumLibro;

  